### ISSUE TITLE
tvdb.Series_Episodes(id).all() only works once

### ISSUE THREAD

**Issue by 3lixy** [phate89/tvdbsimple#2]
After the first use of Series_Episodes it seems not to do anything apart from return an empty list.
In my application i have the debug http requests logged and only see a request made to the api endpoint on the first use of Series_Episodes.

Python 2.7.9
tvdbsimple==1.0.4

Example code to replicate the issue:

```
import tvdbsimple as tvdb
if __name__ == '__main__':
    tvdb.KEYS.API_KEY = 'your_api_key'
    eids = [78804, 281662, 267440]
    for eid in eids:
        blah = tvdb.Series_Episodes(eid).all()
        print(len(blah))
```

281
0
0

```
import tvdbsimple as tvdb
if __name__ == '__main__':
    tvdb.KEYS.API_KEY = 'your_api_key'
    eids = [78804, 281662, 267440]
    for eid in eids:
        blah = tvdb.Series(eid)
        bloo = blah.Episodes.all()
        print(len(bloo))
```

281
0
0

this works fine though

```
import tvdbsimple as tvdb
if __name__ == '__main__':
	tvdb.KEYS.API_KEY = 'your_api_key'
	eids = [78804, 281662, 267440]
	for eid in eids:
		blah = tvdb.Series_Images(eid).summary()
		print(len(blah))
```
5
4
5

**Comment by 3lixy** [comment]
I think found the issue and I have fixed it locally. Please accept the pull request or fix your own way and push a new release to https://pypi.python.org/pypi as my application depends on this fix.

Pull request here: https://github.com/phate89/tvdbsimple/pull/3

The issue could be the same case with other classes in this project.

**Comment by SteveFanner** [comment]
Having the same issues too.

**Comment by tlc** [comment]
Same here.  I can confirm that @3lixy's fix works.  (Thanks!)  But I'm guessing that making those object variables instead of class variables is a better fix.

Rather than pulling 3lixy's version, I am working around it like this:
```
    tvdb.Series_Episodes._FILTERS = {}
    tvdb.Series_Episodes._PAGES = -1
    tvdb.Series_Episodes._PAGES_LIST = {}
    showeps = tvdb.Series_Episodes(series['id'],
```

**Comment by phate89** [comment]
Should be fixed now and I switched everywhere to instance variables
