### ISSUE TITLE
Response Type

### ISSUE THREAD

**Issue by parthk5** [phate89/tvdbsimple#4]
Hi I love what you do and love this library!!!

I have one problem:

my code:

search = tvdb.Search()
response = search.series("doctor who")

The response is a list type.
How do I convert it into a dict or dictionary type??

**Comment by rmartin16** [comment]
The response is a List of one or more Dictionaries. You can iterate through the list to access each dictionary.

For instance:
```
for show in response:
    print(show['seriesName'])
```
