### ISSUE TITLE
Exception during exception handling.

### ISSUE THREAD

**Issue by tlc** [phate89/tvdbsimple#5]
When using the following bad data request (there is no episode 15),

```
showeps = tvdb.Series_Episodes(78874, airedSeason=1, airedEpisode=15)
eps = showeps.all()
```

I saw an exception during the exception handling

```
  File "/home/troy/.local/lib/python3.5/site-packages/tvdbsimple/base.py", line 144, in _request
    raise Exception(response.json()['error'])
KeyError: 'error'
```

**Comment by tlc** [comment]
The response.json() was

> 
{'Error': 'No results for your query: map[EpisodeNumber:15 Season:1 tve.seriesId:78874]'}

**Comment by phate89** [comment]
It's a case error. https://github.com/phate89/tvdbsimple/pull/8 will fix it
