### ISSUE TITLE
Authentication errors

### ISSUE THREAD

**Issue by darryllane** [phate89/tvdbsimple#6]
So I am attempt a simple search as per below. I keep getting Auth issues, even tho the key is fine. I couldnt find where to set username and userkey but I tried hard coding them on the init but same issue.  Im using python3.7

```
import tvdbsimple as tvdb
tvdb.KEYS.API_KEY = 'RCNBQO6OM61NLMWX'
search = tvdb.Search()
search.series("Dragon Ball")
for item in search.series:
	print(item['seriesName'])
```

**Comment by darryllane** [comment]
After some testing I found if I havent set the UA to something non standard (using requests the default is User-Agent: python-requests/2.9.1). Each request response is a 403, chaning the UA to a normal windows UA resolves the problem.

**Comment by speedyflipper** [comment]
I'm having the same issue. How did you change the user agent?
