### ISSUE TITLE
Many Bugs and Pitfalls...FYI

### ISSUE THREAD

**Issue by rmartin16** [phate89/tvdbsimple#7]
For anyone finding this in the future, below are the issues I've found with this package...they are manageable but annoying. Not sure if the original author is responding to pull requests anymore. I can make one if so, though.

series.py
    Series_Episodes:
        - fixed _URLS{'queryparams'} to _URLS{'query_params'} so Series_Episodes.query_params() actually works
        - converted _PAGES, _PAGES_LIST, and _FILTERS from class members to instance members so calls to Series_Episodes works more than once
    Series_Images
        - fixed _URLS{'queryparams'} to _URLS{'query_params'} so Series_Images.query_params() actually works
        - Series_Images.all() bombs out if no filters are set
        - call summary(), the other methods break since they have become integer attributes
        - once one of the other methods is called, that method becomes a attribute of the response and thus uncallable

updates.py
    Updates:
        - fixed _URLS{'params'} __init__ to _URLS{'update_params'} so Updates.update_params() actually works
        - series can only be called once since it becomes a attribute after the first call...

search.py
    Search
        - fixed _URLS{'seriesparams'} to _URLS{'series_params'} so Search.series_params() actually works
        - series can only be called once since it becomes an attribute after the first call

user.py
    User_Ratings
        - converted _PAGES, _PAGES_LIST, and _FILTERS from class members to instance members so calls to User_Ratings works more than once

base.py
    TVDB
        - if_requests gets a 404 back, raise Exception(response.json()['error']) blows up since 'error' isn't a valid key. should be 'Error'
            - this is an awkward Exception anyway since its raised in a Try block and then a call to requests raises another exception...

**Comment by dremy7** [comment]
nice work, rmartin16. This really is a nice little library when it works properly. I'm pretty sure the original creator has abandoned it, though. You might want to consider just forking it.

**Comment by phate89** [comment]
Sorry but I really had no time and missed the reply altogether.. can you provide a pr? So I could merge it and give you credit 
Edit: I missed your pr.. I'll do a review and merge it

**Comment by rmartin16** [comment]
PR is being reviewed now. Thanks @dremy7 and @phate89.
